services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_DB: ribbony
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  ribbony-config-server:
    image: ribbony-config-server
    container_name: ribbony-config-server
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  ribbony-backend:
    image: ribbony-backend
    container_name: ribbony-backend
    ports:
      - "9092:9092"
    depends_on:
      ribbony-config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ribbony
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    volumes:
      - ./logs/backend:/app/logs

volumes:
  postgres_data: